### ISSUE TITLE
meta: batch send task list

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#420]
Here's what's left to deploy batch sends to production:

- [x] @mds1 to fix umbra-js tests and CI to facilitate the rest of the tasks —done in https://github.com/ScopeLift/umbra-protocol/pull/421
- [x] @garyghayrat to add the required umbra-js https://github.com/ScopeLift/umbra-protocol/pull/426
- [x] And frontend code across 2-3 PRs, concluding with #413  (sample UI is shown in https://github.com/ScopeLift/umbra-protocol/issues/298)
- [x] @apbendi to update periphery contract deploy scripts to have a `ScriptBase` contract that holds an array of all networks we're deployed on, and loops through them all using `createSelectFork` to (1) see if contract exists at expected address on chain, and (2) if it doesn't deploy it. Can use the forge-std `StdChains` helpers to facilitate this (but I recommend [turning off](https://github.com/foundry-rs/forge-std/blob/fc560fa34fa12a335a50c35d92e55a6628ca467c/src/StdChains.sol#L180) the fallback default RPCs, since they can be flaky)
- [x] ScopeLift to internally review the contract for security/safety
- [ ] Consider a small C4 contest for external review

**Comment by mds1** [comment]
Note I closed the draft PRs of https://github.com/ScopeLift/umbra-protocol/pull/413 and https://github.com/ScopeLift/umbra-protocol/pull/431 since we're planning to merge #290 first
