### ISSUE TITLE
Tracking Issue: Gnosis Chain Deployment

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/umbra-protocol#514]
- [x] Deploy contracts using [deploy script](https://github.com/ScopeLift/umbra-protocol/blob/master/contracts-core/scripts/deploy.js)
- [x] Configure and deploy subgraph for Gnosis Chain
- [x] Add Gnosis Chain support to frontend (see [this pr](https://github.com/ScopeLift/umbra-protocol/pull/293/files) for hints from last time)
- [x] Add Gnosis Chain to backend with base asset only (xDai)
- [x] Ship Gnosis Chain support with base asset only to production
- [x] Stand up a Gnosis Chain relayer, identify top non-base-asset tokens on the chain and add support to the backend (likely candidates: WETH, WBTC, GNO, other stablecoins?)

See [this checklist](https://github.com/ScopeLift/umbra-protocol/issues/281)

**Comment by apbendi** [comment]
Contracts deployed and verified:

* [0xfb2dc580eed955b528407b4d36ffafe3da685401](https://gnosisscan.io/address/0xfb2dc580eed955b528407b4d36ffafe3da685401#code)
* [0x31fe56609c65cd0c510e7125f051d440424d38f3](https://gnosisscan.io/address/0x31fe56609c65cd0c510e7125f051d440424d38f3#code)

**Comment by apbendi** [comment]
Subgraph for Gnosis Chain available here: https://api.goldsky.com/api/public/project_clfmn098ebuoc3svybn2l2tvp/subgraphs/umbra-xdai/v1.0.0/gn
